### ISSUE TITLE
Question about development

### ISSUE THREAD

**Issue by br4yd** [Badbird5907/AntiCombatLog#14]
Hello,
just a short question: Do you still maintain this project or won't there be future updates from you, so updates depend on forks?
Thank you in advance!

**Comment by Badbird5907** [comment]
I have plans to completely rewrite the plugin when I have time (Around this winter break). 
So yes, I still maintain this project.

**Comment by Badbird5907** [comment]
Update: Rewrite started on the [rewrite](https://github.com/Badbird5907/AntiCombatLog/tree/rewrite) branch.

**Comment by br4yd** [comment]
Thank you very much!
