### ISSUE TITLE
Whenever the player disconnects, a hologram appears without an NPC

### ISSUE THREAD

**Issue by Tomasekg15** [Badbird5907/AntiCombatLog#19]
Basically what the title says,

I am using Arclight on 1.19.2. There are no errors in the console, everything loads as it should. The Citizens version I am using is 2.0.30-b2791 and the Combat Log Plugin is 2.3.0. I tried everything! And I just can't get it to work... After the player logs off, there is just a yellow text saying "15 seconds left", and no NPC.
![2023-04-26_22 03 01](https://user-images.githubusercontent.com/62138046/234689573-629c95a4-98a0-4f01-91a3-77248ae77908.png)

help? please?

**Comment by Badbird5907** [comment]
Honestly I think it's arclight, try with a spigot/paper server. Also check if you can spawn a npc with citizens via `/npc`

**Comment by Badbird5907** [comment]
citizens just doesn't work on arclight.
![image](https://github.com/Badbird5907/AntiCombatLog/assets/50347938/30acc0ec-8552-4b5d-b830-aa0c470700f9)
