### ISSUE TITLE
NPC name is random characters - messing up death messages

### ISSUE THREAD

**Issue by sudothefox** [Badbird5907/AntiCombatLog#6]
Using version 2.1.0.
Paper version:
```This server is running Paper version git-Paper-160 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 919e594)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-152 (MC: 1.18.1)
```
Image shows issue:

 ![image](https://user-images.githubusercontent.com/77643321/150056752-f8d533aa-8420-4529-b24b-9d31b510c409.png)

**Comment by Badbird5907** [comment]
Looks like a citizens thing and out of my control, 
![image](https://user-images.githubusercontent.com/50347938/150663081-2598f2cd-5737-499c-9ab7-cdb70d33961e.png)

Two potential solutions (that both include modifying your death messages plugin):
 1. Ask the author of your death messages plugin to add citizens support (pseudo code below)
 2. Ask the author of the death messages plugin to add AntiCombatLog as a softdepend and use CombatLogKillEvent (the UUID is supplied so they would need to call `Bukkit.getOfflinePlayer(event.getPlayer()).getName()`

Pseudo code for first solution:
```java
    @EventHandler
    public void onKill(PlayerDeathEvent event) {
        if (event.getEntity().hasMetadata("NPC")) {
            String name = CitizensAPI.getNPCRegistry().getNPC(event.getEntity()).getName();
            //handle name here
        }
    }
```
