### ISSUE TITLE
kill-message and log-in-after-kill messages are not working

### ISSUE THREAD

**Issue by sudothefox** [Badbird5907/AntiCombatLog#7]
Using version 2.1.0
This server is running Paper version git-Paper-160 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 919e594)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-152 (MC: 1.18.1)

2 messages from your plugin don't appear to be working.

kill-message:
log-in-after-kill:

**Comment by Badbird5907** [comment]
could you please elaborate on what part doesn't work?

**Comment by sudothefox** [comment]
They just don't get sent at all. I'll see if I can get more information.

**Comment by Badbird5907** [comment]
fixed in 7d200a6dbb564783948929dcd35f50a853c785ae

**Comment by Badbird5907** [comment]
nevermind
